#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v25
# autospec commit: 9594167
#
Name     : R-shinydashboard
Version  : 0.7.3
Release  : 45
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/shinydashboard_0.7.3.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/shinydashboard_0.7.3.tar.gz
Summary  : Create Dashboards with 'Shiny'
Group    : Development/Tools
License  : MIT
Requires: R-htmltools
Requires: R-promises
Requires: R-shiny
BuildRequires : R-htmltools
BuildRequires : R-promises
BuildRequires : R-shiny
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
on top of 'Shiny', making it easy to create attractive dashboards.

%prep
%setup -q -n shinydashboard
pushd ..
cp -a shinydashboard buildavx2
popd
pushd ..
cp -a shinydashboard buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1745332357

%install
export SOURCE_DATE_EPOCH=1745332357
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/shinydashboard/AdminLTE/AdminLTE.css
/usr/lib64/R/library/shinydashboard/AdminLTE/AdminLTE.min.css
/usr/lib64/R/library/shinydashboard/AdminLTE/LICENSE.txt
/usr/lib64/R/library/shinydashboard/AdminLTE/_all-skins.css
/usr/lib64/R/library/shinydashboard/AdminLTE/_all-skins.min.css
/usr/lib64/R/library/shinydashboard/AdminLTE/app.js
/usr/lib64/R/library/shinydashboard/AdminLTE/app.js.map
/usr/lib64/R/library/shinydashboard/AdminLTE/app.min.js
/usr/lib64/R/library/shinydashboard/AdminLTE/app.min.js.map
/usr/lib64/R/library/shinydashboard/AdminLTE/fonts/LICENSE.txt
/usr/lib64/R/library/shinydashboard/AdminLTE/fonts/Source_Sans_Pro_300.ttf
/usr/lib64/R/library/shinydashboard/AdminLTE/fonts/Source_Sans_Pro_300italic.ttf
/usr/lib64/R/library/shinydashboard/AdminLTE/fonts/Source_Sans_Pro_400.ttf
/usr/lib64/R/library/shinydashboard/AdminLTE/fonts/Source_Sans_Pro_400italic.ttf
/usr/lib64/R/library/shinydashboard/AdminLTE/fonts/Source_Sans_Pro_600.ttf
/usr/lib64/R/library/shinydashboard/AdminLTE/fonts/Source_Sans_Pro_600italic.ttf
/usr/lib64/R/library/shinydashboard/AdminLTE/fonts/Source_Sans_Pro_700.ttf
/usr/lib64/R/library/shinydashboard/DESCRIPTION
/usr/lib64/R/library/shinydashboard/INDEX
/usr/lib64/R/library/shinydashboard/LICENSE
/usr/lib64/R/library/shinydashboard/Meta/Rd.rds
/usr/lib64/R/library/shinydashboard/Meta/features.rds
/usr/lib64/R/library/shinydashboard/Meta/hsearch.rds
/usr/lib64/R/library/shinydashboard/Meta/links.rds
/usr/lib64/R/library/shinydashboard/Meta/nsInfo.rds
/usr/lib64/R/library/shinydashboard/Meta/package.rds
/usr/lib64/R/library/shinydashboard/NAMESPACE
/usr/lib64/R/library/shinydashboard/NEWS.md
/usr/lib64/R/library/shinydashboard/R/shinydashboard
/usr/lib64/R/library/shinydashboard/R/shinydashboard.rdb
/usr/lib64/R/library/shinydashboard/R/shinydashboard.rdx
/usr/lib64/R/library/shinydashboard/help/AnIndex
/usr/lib64/R/library/shinydashboard/help/aliases.rds
/usr/lib64/R/library/shinydashboard/help/paths.rds
/usr/lib64/R/library/shinydashboard/help/shinydashboard.rdb
/usr/lib64/R/library/shinydashboard/help/shinydashboard.rdx
/usr/lib64/R/library/shinydashboard/html/00Index.html
/usr/lib64/R/library/shinydashboard/html/R.css
/usr/lib64/R/library/shinydashboard/shinydashboard.css
/usr/lib64/R/library/shinydashboard/shinydashboard.js
/usr/lib64/R/library/shinydashboard/shinydashboard.js.map
/usr/lib64/R/library/shinydashboard/shinydashboard.min.js
/usr/lib64/R/library/shinydashboard/shinydashboard.min.js.map
